project:
  type: website

website:
  title: "Ridwan Suleiman Adejumo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      # - about.qmd

format:
  html:
    include-in-header:
        - text: |
            <meta name="facebook-domain-verification" content="8luugmgy396prvnkw88loby9shkt6p" />


    theme:
      light: pulse
      dark: slate
    css: styles.css
    toc: true
  

editor: visual



